# Generated by Django 5.2.17 on 2026-10-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20260922_2146"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="store_description",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="store_logo",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="store_name",
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="gstin",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
