# Generated by Django 5.2.17 on 2026-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_vendorprofile_store_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="account_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="business_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="pan",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="return_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="shipping_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="shipping_method",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="store_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="gstin",
            field=models.CharField(max_length=15),
        ),
    ]
